/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uaspraksd;

import javax.swing.JTextField;
import javax.swing.JTextArea;

/**
 *
 * @author AULIA NUR RACHMATIKA
 */
public class kursi extends javax.swing.JFrame {
private final  FINISH fh=new FINISH();
    /**
     * Creates new form kursi
     */
    public kursi() {
        initComponents();
    }
   

    
    public void SetNama(JTextField txt_nama, JTextField txt_no, JTextField txt_tgl_psn, JTextField txt_jam_pesan, JTextField txt_kode, JTextField txt_ka, JTextField txt_nama_ka, JTextField txt_tgl_brkt,JTextField txt_awal, JTextField txt_tiba, JTextField txt_kelas) {
        txt_dat.setText("Nama: " + txt_nama.getText()+"\n"
                +"No.Telpon: " + txt_no.getText()+"\n"
                +"Tanggal Pemesanan: " + txt_tgl_psn.getText()+"\n"
                +"Jam Pemesanan: " + txt_jam_pesan.getText()+"\n"
                +"Kode Booking: " + txt_kode.getText()+"\n"
                +"No.Ka: " + txt_ka.getText()+"\n"
                +"Nama KA: " + txt_nama_ka.getText()+"\n"
                +"Tanggal Keberangkatan: " + txt_tgl_brkt.getText()+"\n"
                +"Stasiun/Jam Berangkat: " + txt_awal.getText()+"\n"
                +"Stasiun/Jam Tiba: " + txt_tiba.getText()+"\n"
                +"Kelas: " + txt_kelas.getText());
    }
   public void kursi (JTextArea kursi, JTextField textField){
      txt_kursi.setText("      A  B  C    D E"
                   +"\n"+"1.   0  0  0    # 0 "
                   +"\n"+" 2.  0  0  0    # 0 "
                   +"\n"+" 3.  0  0  0    # 0 "
                   +"\n"+" 4.  0  0  0    0 0 "
                   +"\n"+" 5.  0  0  0    0 0 "
                   +"\n"+" 6.  0  0  0    0 0 "
                   +"\n"+" 7.  0  0  0    0 0 "
                   +"\n"+" 8.  0  0  0    0 0 "
                   +"\n"+" 9.  0  #  #    0 0 "
                   +"\n"+"10. 0  0  0    0 0"
                  +"\n"+"11. 0  0  0    0 0"
                  +"\n"+"12. 0  0  0    # #"
                  +"\n"+"13  0  0  0    0 0"
                  +"\n"+"14. 0  0  0    # 0 "
                  +"\n"+"15. 0  0  0    0 #"
                  +"\n"+"16. 0  0  0    0 0"
                  +"\n"+"17. 0  0  0    0 0"
                  +"\n"+"18. 0  0  0    0 0"
                  +"\n"+"19. 0  0  0    0 0"
                  +"\n"+"20. 0  0  0    0 0");
      txt_pilih.setText(""+textField.getText()+"/ ");

      
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_kursi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_dat = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txt_pilih = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_penumpang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KURSI");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 175, 80, 20));

        txt_kursi.setColumns(20);
        txt_kursi.setRows(5);
        jScrollPane1.setViewportView(txt_kursi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, -1, 356));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATA PENUMPANG");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 240, -1));

        txt_dat.setColumns(20);
        txt_dat.setFont(new java.awt.Font("Monospaced", 3, 12)); // NOI18N
        txt_dat.setRows(5);
        jScrollPane2.setViewportView(txt_dat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 261, 378));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SILAHKAN PILIH KURSI YANG INGIN ANDA TEMPATI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 370, 40));

        txt_pilih.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txt_pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pilihActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 151, 34));

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HARGA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 117, -1, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUMLAH PENUMPANG");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL BAYAR");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, 23));

        txt_harga.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        getContentPane().add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 140, 30));

        txt_total.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 140, 30));

        txt_penumpang.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        txt_penumpang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_penumpangKeyReleased(evt);
            }
        });
        getContentPane().add(txt_penumpang, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 140, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspraksd/ka.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspraksd/index.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_pilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pilihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pilihActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fh.last(txt_dat);
        fh.biaya(txt_harga, txt_penumpang, txt_total);
        fh.kursi(txt_pilih);
        fh.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void txt_penumpangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_penumpangKeyReleased
        // TODO add your handling code here:
         int a, b, c;
        a = Integer.valueOf(txt_harga.getText());
        b = Integer.valueOf(txt_penumpang.getText());
        c = a * b;
        txt_total.setText(String.valueOf(c));
    }//GEN-LAST:event_txt_penumpangKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kursi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kursi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_dat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextArea txt_kursi;
    private javax.swing.JTextField txt_penumpang;
    private javax.swing.JTextField txt_pilih;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables

    void SetNama(JTextField txt_nama, JTextField txt_no, JTextField txt_tgl_psn, JTextField txt_jam_pesan, JTextField txt_kode, JTextField txt_ka, JTextField txt_nama_ka, JTextField txt_tgl_brkt, JTextField txt_tiba, JTextField txt_kelas) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
