/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uaspraksd;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author AULIA NUR RACHMATIKA
 */
public class loket extends javax.swing.JFrame {
private final data dtafinal= new data();
    Queue antri = new LinkedList<>();
    Queue namaantrian = new LinkedList<>();
    int nomer = 0;

    public loket() {
        initComponents();

    }

    public void ambilNomor() {


        if (txt_nama.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan Nama");
        } else {
            nomer++;
            String NoAntri = "ANTRIAN KE " + nomer;
            String nama = txt_nama.getText();
            namaantrian.add(nama);
            antri.add(NoAntri);

            lbl_no.setText((String) antri.peek());//memproses data yang dimasukkan pertama

            lbl_nama.setText((String) namaantrian.peek());
            lbl_nama.getText();

            txt_antrian.append(nama + "\n");

        }
    }
    public void panggilAntrian(){
        if(antri.isEmpty()){//melihat antriaan apakah kosong atau tidak
            JOptionPane.showMessageDialog(null, "SILAKAN AMBIL NOMER ANTRIAN");
        }
        txt_antrian.setText("");
        antri.poll();//mengeluarkan antrian paling depan dan akan null jika antrian kosong
        namaantrian.poll();
        namaantrian.forEach((Object element) -> {
        txt_antrian.append(element +"\n");
    });
        if (antri.isEmpty()){
            lbl_no.setText("ANTRIAN KOSONG");
            lbl_nama.setText("------");
        }else{
            lbl_nama.setText(""+namaantrian.peek());
            lbl_no.setText(""+antri.peek());
        }
     
        
    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btn_ambilNmr = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_antrian = new javax.swing.JTextArea();
        btn_panggil = new javax.swing.JButton();
        lbl_nama = new javax.swing.JLabel();
        lbl_no = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollBar2 = new javax.swing.JScrollBar();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspraksd/index.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ambilNmr.setText("AMBIL NOMOR ANTRIAN");
        btn_ambilNmr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ambilNmrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ambilNmr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 170, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspraksd/ka.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 100));

        jLabel3.setFont(new java.awt.Font("Swis721 Hv BT", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setText("LOKET STASIUN BOJONEGORO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 940, 100));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ISI NAMA ANTRIAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 150, 200, -1));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 240, 50));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DAFTAR ANTRIAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        txt_antrian.setColumns(20);
        txt_antrian.setRows(5);
        txt_antrian.setText("\n\n\n\n");
        jScrollPane1.setViewportView(txt_antrian);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 170, 320));

        btn_panggil.setText("PANGGIL ANTRIAN");
        btn_panggil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_panggilActionPerformed(evt);
            }
        });
        getContentPane().add(btn_panggil, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        lbl_nama.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
        lbl_nama.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nama.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 255)));
        getContentPane().add(lbl_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, 150));

        lbl_no.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 24)); // NOI18N
        lbl_no.setForeground(new java.awt.Color(255, 255, 255));
        lbl_no.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 255)));
        getContentPane().add(lbl_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 220, 130));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 50, -1));
        getContentPane().add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, -1, -1));
        getContentPane().add(jScrollBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 90, 40));

        jButton1.setText("INPUT DATA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uaspraksd/index.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ambilNmrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ambilNmrActionPerformed
        ambilNomor();


    }//GEN-LAST:event_btn_ambilNmrActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_panggilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_panggilActionPerformed
        // TODO add your handling code here:
        panggilAntrian();
    }//GEN-LAST:event_btn_panggilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dtafinal.SetName(lbl_no);
        
        dtafinal.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ambilNmr;
    private javax.swing.JButton btn_panggil;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_no;
    private javax.swing.JTextArea txt_antrian;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
